let pokemonTypeTranslater = {
    "normal": "Normal",
    "fighting": "Kampf",
    "flying": "Flug",
    "poison": "Gift",
    "ground": "Boden",
    "rock": "Gestein",
    "bug": "Käfer",
    "ghost": "Gespenst",
    "steel": "Stahl",
    "fire": "Feuer",
    "water": "Wasser",
    "grass": "Pflanze",
    "electric": "Elektro",
    "psychic": "Psycho",
    "ice": "Eis",
    "dragon": "Drache",
    "dark": "Unlicht",
    "fairy": "Fee"
};